package com.example.vesta.data.models.product

import androidx.collection.IntIntMap
import com.example.vesta.data.models.OctStickers
import com.example.vesta.domain.modelsUI.OctStickersUi

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

data class ProductResponseUi(
    val attributes: List<AttributeUi>,
    val category: CategoryUi,
    val dateAdded: String,
    val dateAvailable: String,
    val dateModified: String,
    val description: ProductDescriptionUi,
    val ean: String,
    val height: String,
    val image: String,
    val images: List<ImageUi>,
    val isbn: String,
    val jan: String,
    val lastSyncAt: String,
    val length: String,
    val lengthClassId: Int,
    val location: String,
    val manufacturer: ManufacturerUi,
    val manufacturerId: Int,
    val minimum: Int,
    val model: String,
    val mpn: String,
    val multistoreProduct: MultistoreProductUi,
    val octStickers: OctStickersUi,
    val onesUuid: String,
    val points: Int,
    val productId: Int,
    val quantityLen117: Int,
    val related: List<RelatedUi>,
    val reviews: List<ReviewUi>,
    val shipping: Int,
    val sku: String,
    val sortOrder: Int,
    val status: Int,
    val stockStatusId: Int,
    val store: List<StoreUi>,
    val subtract: Int,
    val taxClassId: Int,
    val upc: String,
    val viewed: Int,
    val weight: String,
    val weightClassId: Int,
    val width: String,
    val isFavorite: Boolean
) {
    companion object {
        val empty = ProductResponseUi(
            attributes = emptyList(),
            category = CategoryUi.empty,
            dateAdded = "",
            dateAvailable = "",
            dateModified = "",
            description = ProductDescriptionUi.empty,
            ean = "",
            height = "",
            image = "",
            images = emptyList(),
            isbn = "",
            jan = "",
            lastSyncAt = "",
            length = "",
            lengthClassId = 0,
            location = "",
            manufacturer = ManufacturerUi.empty,
            manufacturerId = 0,
            minimum = 0,
            model = "",
            mpn = "",
            multistoreProduct = MultistoreProductUi.empty,
            octStickers = OctStickersUi.empty,
            onesUuid = "",
            points = 0,
            productId = 0,
            quantityLen117 = 0,
            related = emptyList(),
            reviews = emptyList(),
            shipping = 0,
            sku = "",
            sortOrder = 0,
            status = 0,
            stockStatusId = 0,
            store = emptyList(),
            subtract = 0,
            taxClassId = 0,
            upc = "",
            viewed = 0,
            weight = "",
            weightClassId = 0,
            width = "",
            isFavorite = false
        )
    }
}

data class MultistoreProductUi(
    val dateAdded: String,
    val dateModified: String,
    val id: Int,
    val lastSyncAt: String,
    val price: Int,
    val priceM: Int,
    val priceP: String,
    val pricer: Int,
    val productId: Int,
    val quantity: Int,
    val spb1: Int,
    val spb2: Int,
    val spb3: Int,
    val spb4: Int,
    val spb5: Int,
    val spb6: Int,
    val spb7: Int,
    val spb8: Int,
    val spb9: Int,
    val spb10: Int,
    val spb11: Int,
    val spb12: Int,
    val spb13: Int,
    val spb14: Int,
    val spb15: Int,
    val spb16: Int,
    val stockStatusId: Int,
    val storeId: Int,
) {
    companion object {
        val empty =  MultistoreProductUi(
            dateAdded = "",
            dateModified = "",
            id= 0,
            lastSyncAt= "",
            price= 0,
            priceM= 0,
            priceP= "",
            pricer= 0,
            productId= 0,
            quantity= 0,
            spb1 = 0,
            spb2 = 0,
            spb3 = 0,
            spb4 = 0,
            spb5 = 0,
            spb6 = 0,
            spb7 = 0,
            spb8 = 0,
            spb9 = 0,
            spb10 = 0,
            spb11 = 0,
            spb12 = 0,
            spb13 = 0,
            spb14 = 0,
            spb15 = 0,
            spb16 = 0,
            stockStatusId = 0,
            storeId = 0,
        )
    }

}
